global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api_gateway'
    consul_sd_configs:
      - server: 'consul:8500'
        services: ['api_gateway']
    metrics_path: '/metrics'

  - job_name: 'data_simulator'
    consul_sd_configs:
      - server: 'consul:8500'
        services: ['data_simulator']
    metrics_path: '/metrics'

  - job_name: 'cashflow_predictor'
    consul_sd_configs:
      - server: 'consul:8500'
        services: ['cashflow_predictor']
    metrics_path: '/metrics'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 